### ISSUE TITLE
What is the policy for including “foreign” kubernetes schemas, like spv.no/v1alpha1?

### ISSUE THREAD

**Issue by ghost** [arianvp/dhall-kubernetes#124]
This https://github.com/SparebankenVest/azure-key-vault-to-kubernetes is used in production left and right. As an example object, it allows defining mapping between Azure KeyVault and Kubernetes Secret Store:

```yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync-my-secret
  namespace: default
spec:
  vault:
    name: somexamplevault
    object:
      name: my-secret # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: my-secret-from-akv # kubernetes secret name
      dataKey: secret-value # key to store object value in kubernetes secret
```

Generating this from Dhall is invaluable (as one could guess) because by hand, maintaining mappings is quickly a mess.

My question is: should this sort of thing at some point make it to this repo, or should this be a separated project?
