### ISSUE TITLE
The Deployment "name" is invalid .. envFrom: Invalid value: "": may not have more than one field specified at a time

### ISSUE THREAD

**Issue by mokshasoft** [arianvp/dhall-kubernetes#167]
I am not sure where to post this problem or bug (dhall-lang, dhall-openshift, dhall-kubernetes, or something else). I'm very new to Dhall and Kubernetes, and I'm trying to port a yaml configuration to dhall-kubernetes.

OpenShift: 4.6.21
Kubernetes: v1.19.0+2f3101c

Trying to apply the generated yaml-file fails:
```
oc apply -f Dhall/deployments.yaml
The Deployment "name" is invalid: spec.template.spec.containers[0].envFrom: Invalid value: "": may not have more than one field specified at a time
```

Since the file below type-checks I hoped that it would also be a correct configuration. And I thought that that would be an advantage with Dhall? Of course it depends on if the configuration of kubernetes has been correctly specified in dhall-kubernetes.

It would be interesting if a dhall-X project could be used as a basis for generating the configuration code in the application we are trying to configure. Then the dhall-X project would be the single-source-of-truth regarding an application X's configuration.

Dhall/deployments.dhall
```
let kubernetes =
      https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/1.19/package.dhall

let deployment
      : kubernetes.Deployment.Type =
      let app : Text = "app"
      let name : Text = "name"
      in
        kubernetes.Deployment::{
        , metadata = kubernetes.ObjectMeta::{     
          , name = Some name
          , labels = Some (toMap { app = app })
          }
        , spec = Some kubernetes.DeploymentSpec::{
          , replicas = Some +1                    
          , selector = kubernetes.LabelSelector::{    
            , matchLabels = Some (toMap { app = app })
            }                                       
          , template = kubernetes.PodTemplateSpec::{
            , metadata = Some kubernetes.ObjectMeta::{
              , labels = Some (toMap { app = app })
              }                                
            , spec = Some kubernetes.PodSpec::{
              , containers =             
                [ kubernetes.Container::{                             
                  , envFrom = Some                                  
                    [ kubernetes.EnvFromSource::{                           
                      , secretRef = Some kubernetes.SecretEnvSource::{      
                        , name = Some "jobtech-taxonomy-api-secrets"
                        }                                                   
                      , configMapRef = Some kubernetes.ConfigMapEnvSource::{
                        , name = Some "datomic-config"
                        }               
                      }                            
                    ]                              
                  , name = name         
                  , image = Some "image"           
                  , imagePullPolicy = Some "Always"
                  , ports = Some
                    [ kubernetes.ContainerPort::{
                      , containerPort = +3000
                      , protocol = Some "TCP"
                      }
                    ]
                  }
                ]                                
              }                                       
            }                                
          }            
        }
                     
in deployment      
```

Gets converted to Dhall/deployments.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: datomic-config
              secretRef:
                name: jobtech-taxonomy-api-secrets
          image: image
          imagePullPolicy: Always
          name: name
          ports:
            - containerPort: 3000
              protocol: TCP
```

Adding a dash '-' infront of secretRef in the generated yaml-file, makes 'oc apply -f Dhall/deployments.yaml' pass without errors.
```
        - envFrom:
            - configMapRef:
                name: datomic-config
            - secretRef:
                name: jobtech-taxonomy-api-secrets
          image: image
          imagePullPolicy: Always
          name: name
          ports:
            - containerPort: 3000
              protocol: TCP
```
