### ISSUE TITLE
How to represent other Resource types, eg. Istio `VirtualService`

### ISSUE THREAD

**Issue by samuela** [arianvp/dhall-kubernetes#187]
Kubernetes tools like Istio require the creation of yaml like
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ska-deleteme-2023-vs
  namespace: ska-deleteme-2023
  annotations:
    external-dns.alpha.kubernetes.io/controller: dns-controller
    external-dns.getcruise.com/zone.class: dns-internal-dev
spec:
  gateways:
    - istio-system/paasapps
  hosts:
    - ska-deleteme-2023.dev.paasapps.robot.car
  http:
    - route:
...
```
Notably, `kind: VirtualService` is not part of kubernetes and `apiVersion` refers to a non-kubernetes api. (See https://istio.io/latest/docs/reference/config/networking/virtual-service/ for more info.)

How can one create this sort of config via dhall-kubernetes? I'm not seeing any sort of `VirtualService` in the dhall-kubernetes `Resource` definitions, which is to be expected since this is Istio-specific nonsense. However, I'm also not able to find any way of extending `k8s.Resource` with extra definitions. 

I'd like to be able to write something along the lines of 
```dhall
let istio =
      { apiVersion = "networking.istio.io/v1beta1"
      , kind = "VirtualService"
      , metadata = { name = "foo", namespace = "bar" }
      ...
      }

in  [ k8s.Resource.Service service, k8s.Resource.Deployment deployment, istio ]
```
but ofc this doesn't work since the type of `istio` is not in the large type union that is all dhall-kubernetes resource types.

How does one accomplish this sort of pattern with dhall-kubernetes?
